Update manually-github-package.yml

diff --git a/.github/workflows/manually-github-package.yml b/.github/workflows/manually-github-package.yml
--- a/.github/workflows/manually-github-package.yml
+++ b/.github/workflows/manually-github-package.yml
@@ -9,30 +9,21 @@ on:
     inputs:
       release_version: 
         required: true
-        description: 'Specific version to use for the package (e.g., 1.0.0, 1.0.0-preview)'
-      release_type:
-        required: true
-        default: true
-        type: boolean
-        description: 'Is Preview'
+        description: 'Specific version to use for the package (e.g., 1.0.0, 1.0.0-preview, 1.0.0-preview.1)'
 
 jobs:
   publish:
     runs-on: ubuntu-latest
 
     steps:
-      - name: Validate Release Version Input
-        # This step runs only if a release_version input is provided via workflow_dispatch.
-        if: github.event.inputs.release_version != '' && github.event.inputs.release_version != null
+      - name: Show Inputs
         run: |
-          VERSION="${{ github.event.inputs.release_version }}"
-          echo VERSION
-          # Regex for basic semantic versioning (e.g., 1.0.0, 1.0.0-beta.1, 1.0.0-rc)
-          if ! echo "$VERSION" | grep -E '^\d+\.\d+\.\d+(-[a-zA-Z0-9\.-]+)?$' > /dev/null; then
-            echo "::error::Invalid 'release_version' format. Expected semantic version (e.g., 1.0.0 or 1.0.0-beta)."
-            exit 1 # Fail the workflow if validation fails
-          else
-            echo "Release version '$VERSION' format is valid."
+          echo "Version: ${{ github.event.inputs.release_version }}"
+
+      - name: Validate Inputs
+        run: |
+          if [[ ! "${{ github.event.inputs.version }}" =~ ^[0-9]+\.[0-9]+\.[0-9]+(-preview\.[0-9]+)?$ ]]; then
+            echo "❌ Invalid version format. Use semver like 1.0.0 or 1.0.0-preview.1"
+            exit 1
           fi
-    
         
